"""Add first_name and last_name columns to users table

Revision ID: 156cf21ef8a1
Revises: 750efb429e88
Create Date: 2026-09-11 05:18:03.376646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '156cf21ef8a1'
down_revision: Union[str, Sequence[str], None] = '750efb429e88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant_payout_accounts', sa.Column('account_holder_name', sa.Text(), nullable=True))
    op.add_column('merchant_payout_accounts', sa.Column('bank_code', sa.String(length=50), nullable=True))
    op.add_column('merchant_payout_accounts', sa.Column('routing_number', sa.String(length=50), nullable=True))
    op.add_column('merchant_payout_accounts', sa.Column('account_type', sa.String(length=20), nullable=True))
    op.add_column('merchant_payout_accounts', sa.Column('country', sa.CHAR(length=2), nullable=True))
    op.create_index('idx_merchant_payout_accounts_country', 'merchant_payout_accounts', ['country'], unique=False)
    op.add_column('merchants', sa.Column('address_line1', sa.Text(), nullable=True))
    op.add_column('merchants', sa.Column('address_line2', sa.Text(), nullable=True))
    op.add_column('merchants', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('merchants', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('merchants', sa.Column('postal_code', sa.String(length=20), nullable=True))
    op.add_column('merchants', sa.Column('country', sa.CHAR(length=2), nullable=True))
    op.create_index('idx_merchants_country', 'merchants', ['country'], unique=False)
    op.drop_index(op.f('idx_orders_created_at'), table_name='orders')
    op.create_index('idx_orders_created_at', 'orders', [sa.literal_column('created_at DESC')], unique=False)
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'NON_BINARY', 'PREFER_NOT_TO_SAY', 'UNSET', name='gender'), server_default='unset', nullable=True))
    op.add_column('users', sa.Column('preferred_language', sa.String(length=10), server_default=sa.text("'en'"), nullable=True))
    op.create_index('idx_users_first_name', 'users', ['first_name'], unique=False)
    op.create_index('idx_users_gender', 'users', ['gender'], unique=False)
    op.create_index('idx_users_last_name', 'users', ['last_name'], unique=False)
    op.create_index('idx_users_preferred_language', 'users', ['preferred_language'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_preferred_language', table_name='users')
    op.drop_index('idx_users_last_name', table_name='users')
    op.drop_index('idx_users_gender', table_name='users')
    op.drop_index('idx_users_first_name', table_name='users')
    op.drop_column('users', 'preferred_language')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_index('idx_orders_created_at', table_name='orders')
    op.create_index(op.f('idx_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.drop_index('idx_merchants_country', table_name='merchants')
    op.drop_column('merchants', 'country')
    op.drop_column('merchants', 'postal_code')
    op.drop_column('merchants', 'state')
    op.drop_column('merchants', 'city')
    op.drop_column('merchants', 'address_line2')
    op.drop_column('merchants', 'address_line1')
    op.drop_index('idx_merchant_payout_accounts_country', table_name='merchant_payout_accounts')
    op.drop_column('merchant_payout_accounts', 'country')
    op.drop_column('merchant_payout_accounts', 'account_type')
    op.drop_column('merchant_payout_accounts', 'routing_number')
    op.drop_column('merchant_payout_accounts', 'bank_code')
    op.drop_column('merchant_payout_accounts', 'account_holder_name')
    # ### end Alembic commands ###
