"""add support tickets and knowledge documents

Revision ID: 541724af8568
Revises: 156cf21ef8a1
Create Date: 2026-09-12 01:17:54.678588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '541724af8568'
down_revision: Union[str, Sequence[str], None] = '156cf21ef8a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_documents',
    sa.Column('doc_type', sa.Enum('POLICY', 'FAQ', 'GUIDE', 'ANNOUNCEMENT', name='doctype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('audience', sa.Enum('BUYER', 'MERCHANT', 'ALL', name='docaudience'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='docstatus'), nullable=False),
    sa.Column('version', sa.String(length=20), server_default='1', nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knowledge_documents_topic', 'knowledge_documents', ['topic'], unique=False)
    op.create_index('idx_knowledge_documents_type_status', 'knowledge_documents', ['doc_type', 'status'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_status'), 'knowledge_documents', ['status'], unique=False)
    # InnoDB requires an index on every FK column (created_by -> users.id)
    op.create_index(op.f('ix_knowledge_documents_created_by'), 'knowledge_documents', ['created_by'], unique=False)
    op.create_table('support_tickets',
    sa.Column('ticket_number', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'TRIAGED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'REOPENED', name='ticketstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='ticketpriority'), nullable=False),
    sa.Column('category', sa.Enum('ORDER_ISSUE', 'PAYMENT', 'REFUND', 'PRODUCT', 'MERCHANT', 'ACCOUNT', 'OTHER', name='ticketcategory'), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requester_user_id', sa.Uuid(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('payment_id', sa.Uuid(), nullable=True),
    sa.Column('merchant_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payment_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_number', name='uq_support_tickets_number')
    )
    op.create_index('idx_support_tickets_requester', 'support_tickets', ['requester_user_id'], unique=False)
    op.create_index('idx_support_tickets_status_created', 'support_tickets', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_support_tickets_assigned_to'), 'support_tickets', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_support_tickets_category'), 'support_tickets', ['category'], unique=False)
    op.create_index(op.f('ix_support_tickets_correlation_id'), 'support_tickets', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_merchant_id'), 'support_tickets', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_order_id'), 'support_tickets', ['order_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_payment_id'), 'support_tickets', ['payment_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_priority'), 'support_tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_support_tickets_session_id'), 'support_tickets', ['session_id'], unique=False)
    op.create_table('support_ticket_events',
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('actor', sa.Enum('AGENT', 'REQUESTER', 'ADMIN', 'SYSTEM', name='ticketeventactor'), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_support_ticket_events_ticket', 'support_ticket_events', ['ticket_id', 'created_at'], unique=False)
    # InnoDB requires an index on every FK column (actor_user_id -> users.id)
    op.create_index(op.f('ix_support_ticket_events_actor_user_id'), 'support_ticket_events', ['actor_user_id'], unique=False)
    # NOTE: autogenerate also emitted a drop/recreate of idx_orders_created_at
    # here. That is MySQL reflection noise for the model's expression index
    # (created_at DESC) — the live index already matches the model, so it is
    # intentionally excluded to keep this migration focused on the new tables.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Drop tables child-first (support_ticket_events.ticket_id -> support_tickets.id).
    # Index drops are intentionally omitted: MySQL/InnoDB refuses to drop an
    # index that serves a foreign key constraint (error 1553), and DROP TABLE
    # removes each table's indexes and FK constraints together.
    op.drop_table('support_ticket_events')
    op.drop_table('support_tickets')
    op.drop_table('knowledge_documents')
    # ### end Alembic commands ###
