"""initial_schema

Revision ID: 750efb429e88
Revises: 04c9b47b55f2
Create Date: 2026-09-07 07:20:50.161092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '750efb429e88'
down_revision: Union[str, Sequence[str], None] = '04c9b47b55f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_orders_created_at'), table_name='orders')
    op.create_index('idx_orders_created_at', 'orders', [sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_orders_created_at', table_name='orders')
    op.create_index(op.f('idx_orders_created_at'), 'orders', ['created_at'], unique=False)
    # ### end Alembic commands ###
